'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/Button';
import { Pill } from '@/components/ui/Pill';
import { Card, CardHeader, CardBody, CardFooter } from '@/components/ui/Card';
import { Input, Textarea } from '@/components/ui/Input';
import { Alert } from '@/components/ui/Alert';
import { Checkbox, Radio, Toggle } from '@/components/ui/Controls';
import { Progress, Avatar, AvatarGroup } from '@/components/ui/Data';
import { Mail, Zap, Download, Camera, Activity, Cpu, Database, Clock, ArrowRight, Check, Info, AlertTriangle, X, ChevronRight, Globe, Layers, Shield } from 'lucide-react';
import { useDesign } from '@/lib/DesignContext';
import { cn } from '@/lib/utils';
import { toPng } from 'html-to-image';

const SectionHeader = ({ num, title, desc }: { num: string; title: string; desc: string }) => (
  <header className="mb-12">
    <span className="font-mono text-[11px] text-[var(--accent-tertiary)] block mb-2">{num}</span>
    <h2 className="font-display text-[34px] font-bold tracking-tight leading-[1.1] mb-2.5 text-[var(--text-main)] transition-colors duration-300">{title}</h2>
    <p className="text-[15px] text-gray-500 dark:text-gray-400 leading-relaxed max-w-[580px] transition-colors duration-300">{desc}</p>
  </header>
);

const Label = ({ children, className }: { children?: React.ReactNode; className?: string }) => (
  <span className={cn('block text-[10px] font-semibold tracking-widest uppercase text-gray-400 dark:text-gray-500 mb-4 transition-colors duration-300', className)}>
    {children}
  </span>
);

export default function Home() {
  const { state } = useDesign();
  const { identity, colors, fonts, radii, theme } = state;
  const pageRef = React.useRef<HTMLDivElement>(null);
  const [isCapturing, setIsCapturing] = React.useState(false);

  const fadeIn = {
    initial: { opacity: 0, y: 8 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.5, ease: [0.25, 0.46, 0.45, 0.94] as [number, number, number, number] }
  };

  const derivedTypefaces = `${fonts.display} · ${fonts.sans} · DM Mono`;

  const handleExport = (type: string) => {
    const brandPrefix = identity.brandName.toLowerCase().replace(/ /g, '-');
    const downloadFile = (filename: string, content: string) => {
      const element = document.createElement('a');
      const file = new Blob([content], { type: 'text/plain' });
      element.href = URL.createObjectURL(file);
      element.download = filename;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    };

    switch (type) {
      case 'CSS':
        const css = `/* ${identity.brandName} Design Tokens */
:root {
  --bg-page: ${theme === 'light' ? '#FAFAFA' : '#0A0A0A'};
  --text-main: ${theme === 'light' ? '#0A0A0A' : '#FAFAFA'};
  --accent-primary: ${colors.primary};
  --accent-secondary: ${colors.secondary};
  --accent-tertiary: ${colors.tertiary};
  --font-display: '${fonts.display}';
  --font-sans: '${fonts.sans}';
  --radius-sm: ${radii.sm}px;
  --radius-md: ${radii.md}px;
  --radius-lg: ${radii.lg}px;
  --radius-xl: ${radii.xl}px;
}`;
        downloadFile(`${brandPrefix}-tokens.css`, css);
        break;
      case 'TW':
        const tw = `// Tailwind Config Snippet
theme: {
  extend: {
    colors: {
      primary: "${colors.primary}",
      secondary: "${colors.secondary}",
      tertiary: "${colors.tertiary}",
    },
    fontFamily: {
      display: ["${fonts.display}", "serif"],
      sans: ["${fonts.sans}", "sans-serif"],
    }
  }
}`;
        downloadFile(`tailwind-config.js`, tw);
        break;
      case 'MD':
        const md = `# ${identity.brandName} — Visual DNA Specification

## 1. Brand Identity
- **Name:** ${identity.brandName}
- **Aesthetic:** ${identity.aesthetic}
- **Typefaces:** ${derivedTypefaces}

## 2. Core Tokens
- **Primary Accent:** \`${colors.primary}\`
- **Secondary Accent:** \`${colors.secondary}\`
- **Tertiary Accent:** \`${colors.tertiary}\`
- **Theme:** \`${theme.toUpperCase()}\`

---
*Generated by Monicore Studio Engine*`;
        downloadFile(`DESIGN.md`, md);
        break;
    }
  };

  const captureScreenshot = React.useCallback(async () => {
    if (pageRef.current === null) return;
    setIsCapturing(true);
    try {
      await document.fonts.ready;
      await new Promise(resolve => setTimeout(resolve, 500));
      const dataUrl = await toPng(pageRef.current, { 
        cacheBust: true, 
        backgroundColor: theme === 'light' ? '#FAFAFA' : '#0A0A0A',
        pixelRatio: 2,
      });
      const link = document.createElement('a');
      link.download = `${identity.brandName.toLowerCase().replace(/ /g, '-')}-design.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) { console.error(err); } finally { setIsCapturing(false); }
  }, [identity.brandName, theme]);

  return (
    <div ref={pageRef} className="sg-container pb-32 transition-colors duration-500 bg-[var(--bg-page)]">
      {/* HERO */}
      <header className="py-24 border-b border-[var(--border-subtle)] mb-20 grid md:grid-cols-2 gap-20 items-center">
        <motion.div {...fadeIn}>
          <p className="text-[11px] font-medium tracking-widest uppercase text-[var(--accent-tertiary)] mb-4">{identity.eyebrow}</p>
          <h1 className="font-display text-[56px] font-black leading-[1.05] tracking-tight mb-5 whitespace-pre-line text-[var(--text-main)] transition-colors duration-300">
            {identity.title}
          </h1>
          <p className="text-[16px] text-gray-500 dark:text-gray-400 leading-relaxed max-w-[480px]">
            {identity.description}
          </p>
        </motion.div>
        <motion.div 
          {...fadeIn} 
          transition={{ ...fadeIn.transition, delay: 0.1 }}
          className="p-8 bg-[var(--bg-surface)] dark:bg-white/5 rounded-lg border border-[var(--border-subtle)] flex flex-col gap-6 transition-colors duration-300 backdrop-blur-md"
        >
          <div className="flex flex-col gap-1">
            <Label className="mb-0.5">Version</Label>
            <span className="text-[13px] font-medium text-gray-600 dark:text-gray-300">{identity.version}</span>
          </div>
          <div className="flex flex-col gap-1">
            <Label className="mb-0.5">Aesthetic</Label>
            <span className="text-[13px] font-medium text-gray-600 dark:text-gray-300">{identity.aesthetic}</span>
          </div>
          <div className="flex flex-col gap-1">
            <Label className="mb-0.5">Primary Typefaces</Label>
            <span className="text-[13px] font-medium text-gray-600 dark:text-gray-300">{derivedTypefaces}</span>
          </div>
          <div className="flex flex-col gap-1">
            <Label className="mb-0.5">Framework</Label>
            <span className="text-[13px] font-medium text-gray-600 dark:text-gray-300">{identity.framework}</span>
          </div>
          <div className="flex flex-col gap-1">
            <Label className="mb-0.5">Status</Label>
            <Pill variant="primary" className="w-fit text-[11px]">{identity.status}</Pill>
          </div>
        </motion.div>
      </header>

      {/* 01 COLORS */}
      <section id="colors" className="sg-section mb-20 pb-20 border-b border-[var(--border-subtle)]">
        <SectionHeader 
          num="01 — Colors" 
          title="Dynamic Palette" 
          desc="Refined accent slots with Auto-Harmony intelligence. Fixed anchors ensure theme stability regardless of palette shifts." 
        />

        <Label>System Anchors</Label>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-12">
          {[
            { name: 'Fixed Black', hex: '#0A0A0A', bg: 'bg-[#0A0A0A]', text: 'text-white' },
            { name: 'Fixed White', hex: '#FAFAFA', bg: 'bg-[#FAFAFA]', border: 'border-gray-200', text: 'text-black' },
            { name: 'Accent Primary', hex: colors.primary, bg: 'bg-[var(--accent-primary)]', text: 'text-[var(--accent-primary-contrast)]' },
            { name: 'Accent Secondary', hex: colors.secondary, bg: 'bg-[var(--accent-secondary)]', text: 'text-[var(--accent-secondary-contrast)]' },
            { name: 'Accent Tertiary', hex: colors.tertiary, bg: 'bg-[var(--accent-tertiary)]', text: 'text-[var(--accent-tertiary-contrast)]' },
          ].map((color) => (
            <div key={color.name} className={cn('p-5 pt-4 rounded-md border-[1.5px] transition-all', color.bg, color.text, color.border)}>
              <div className="text-[12px] font-semibold mb-0.5">{color.name}</div>
              <div className="font-mono text-[11px] opacity-70">{color.hex}</div>
            </div>
          ))}
        </div>

        <Label>Neutral Palette</Label>
        <div className="flex h-14 rounded-md overflow-hidden border border-[var(--border-subtle)] mb-12 transition-colors duration-300">
          {[900, 800, 700, 500, 400, 300, 200, 100, 50].map((step) => (
            <div 
              key={step} 
              className={cn("flex-1 flex items-end p-1.5 text-[9px] font-mono", step > 400 ? "text-gray-400" : "text-gray-600")}
              style={{ backgroundColor: `var(--color-gray-${step})` }}
            >
              {step}
            </div>
          ))}
        </div>

        <Label>Semantic Harmony (Status States)</Label>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
          {[
            { name: 'Success', bg: 'bg-green-light dark:bg-green/10', border: 'border-[#9BD6B8] dark:border-green/30', text: 'text-[#165C38] dark:text-green-light', hex: '#1A7A4A' },
            { name: 'Info', bg: 'bg-[var(--accent-secondary-glass)]', border: 'border-[var(--accent-secondary-glass)]', text: 'text-[var(--accent-secondary)]', hex: colors.secondary },
            { name: 'Warning', bg: 'bg-amber-light dark:bg-amber/10', border: 'border-[#F5D18C] dark:border-amber/30', text: 'text-[#A06308] dark:text-amber-light', hex: '#D4820A' },
            { name: 'Danger', bg: 'bg-[var(--accent-tertiary-glass)]', border: 'border-[var(--accent-tertiary-glass)]', text: 'text-[var(--accent-tertiary)]', hex: colors.tertiary },
          ].map((state) => (
            <div key={state.name} className={cn('p-4 rounded-md border backdrop-blur-sm transition-colors duration-300', state.bg, state.border)}>
              <div className={cn('text-[11px] font-bold tracking-widest uppercase mb-1', state.text)}>{state.name}</div>
              <div className={cn('font-mono text-[12px]', state.text)}>{state.hex}</div>
            </div>
          ))}
        </div>
      </section>

      {/* 02 TYPOGRAPHY */}
      <section id="typography" className="sg-section mb-20 pb-20 border-b border-[var(--border-subtle)]">
        <SectionHeader num="02 — Typography" title="Type System" desc="Dual-surface typography matrix for editorial headings and technical interface clarity." />
        
        <Label>Type Scale</Label>
        <div className="border border-[var(--border-subtle)] rounded-lg overflow-hidden mb-8 bg-[var(--bg-card)] transition-colors duration-300">
          {[
            { tag: 'Display', sample: "There's never been a better iPhone.", styles: 'font-display text-[64px] font-black tracking-[-0.03em] leading-none text-[var(--text-main)]', info: '64px / 900' },
            { tag: 'H1', sample: 'Full-screen display. Built for Intelligence.', styles: 'font-display text-[42px] font-bold tracking-tight leading-[1.1] text-[var(--text-main)]', info: '42px / 700' },
            { tag: 'H2', sample: 'Designed to stand out.', styles: 'font-display text-[30px] font-bold tracking-tight leading-[1.2] text-[var(--text-main)]', info: '30px / 700' },
            { tag: 'H3', sample: 'Performance that redefines expectations', styles: 'text-[22px] font-semibold leading-relaxed text-[var(--text-main)]', info: '22px / 600' },
            { tag: 'Body', sample: 'The quick brown fox jumps over the lazy dog. Readability is the core of our interface language.', styles: 'text-[15px] font-normal leading-relaxed text-[var(--text-main)] max-w-[520px]', info: '15px / 400 / 1.7' },
            { tag: 'Small', sample: 'Supporting text, captions, metadata, helper copy', styles: 'text-[13px] text-gray-500 dark:text-gray-400 leading-normal', info: '13px / 400' },
            { tag: 'Eyebrow', sample: 'PRODUCT LAUNCH · SPRING 2025', styles: 'text-[11px] font-semibold tracking-widest uppercase text-[var(--accent-tertiary)]', info: '11px / 600' },
          ].map((row) => (
            <div key={row.tag} className="flex flex-col md:flex-row md:items-baseline gap-6 p-8 border-b border-[var(--border-subtle)] last:border-b-0 transition-colors duration-300">
              <span className="font-mono text-[11px] text-gray-400 dark:text-gray-600 min-w-[100px]">{row.tag}</span>
              <span className={cn('flex-1 transition-colors duration-300', row.styles)}>{row.sample}</span>
              <span className="text-[11px] text-gray-400 dark:text-gray-600 min-w-[140px] md:text-right">{row.info}</span>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          <div className="p-8 border border-[var(--border-subtle)] rounded-lg bg-[var(--bg-card)] transition-colors">
            <Label className="mb-2">{fonts.display} — Editorial</Label>
            <p className="font-display text-[11px] tracking-widest uppercase text-gray-400 mb-2">{fonts.display.toUpperCase()}</p>
            <p className="font-display text-[36px] font-black tracking-tight leading-none mb-2 text-[var(--text-main)]">Aa Bb Cc</p>
            <p className="font-display text-[18px] italic text-gray-500 mb-4 transition-colors">The art of the possible.</p>
            <p className="font-display text-[13px] text-gray-400 leading-relaxed transition-colors">
              ABCDEFGHIJKLMNOPQRSTUVWXYZ<br />
              abcdefghijklmnopqrstuvwxyz<br />
              0123456789 !@#$%&*()
            </p>
          </div>
          <div className="p-8 border border-[var(--border-subtle)] rounded-lg bg-[var(--bg-card)] transition-colors">
            <Label className="mb-2">{fonts.sans} — Interface</Label>
            <p className="text-[11px] font-semibold tracking-widest uppercase text-gray-400 mb-2">{fonts.sans.toUpperCase()}</p>
            <p className="text-[36px] font-semibold tracking-tight leading-none mb-2 text-[var(--text-main)] transition-colors">Aa Bb Cc</p>
            <p className="text-[18px] font-light text-gray-500 mb-4 transition-colors">Engineered for clarity.</p>
            <p className="text-[13px] text-gray-400 leading-relaxed transition-colors">
              ABCDEFGHIJKLMNOPQRSTUVWXYZ<br />
              abcdefghijklmnopqrstuvwxyz<br />
              0123456789 !@#$%&*()
            </p>
          </div>
        </div>
      </section>

      {/* 03 SPACING */}
      <section id="spacing" className="sg-section mb-20 pb-20 border-b border-[var(--border-subtle)]">
        <SectionHeader num="03 — Spacing" title="Space & Layout" desc="An 8-point base grid system. All decisions derive from multiples of 4px or 8px." />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
          <div className="flex flex-col gap-3">
            {[1, 2, 3, 4, 6, 8, 12, 16, 24].map((s) => (
              <div key={s} className="flex items-center gap-5">
                <div className={cn('h-5 bg-[var(--accent-secondary-glass)] border border-[var(--accent-secondary-glass)] rounded-sm shrink-0')} style={{ width: s * 4 }} />
                <span className="font-mono text-[12px] text-gray-500 dark:text-gray-400 min-w-[80px]">space-{s}</span>
                <span className="text-[12px] text-gray-400 dark:text-gray-600">{s * 4}px</span>
              </div>
            ))}
          </div>
          <div className="flex flex-col gap-10">
            <div className="flex flex-wrap gap-5">
              {['sm', 'md', 'lg', 'xl', 'pill'].map((l) => (
                <div key={l} className={cn('w-18 h-18 bg-[var(--bg-surface)] dark:bg-white/5 border border-[var(--border-subtle)] flex flex-col items-center justify-center text-[10px] text-gray-600 dark:text-gray-400 text-center leading-tight transition-all duration-300', l === 'pill' ? 'rounded-full' : `rounded-${l}`)}>
                  {l}<br />{state.radii[l as keyof typeof state.radii] || '∞'}px
                </div>
              ))}
            </div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-5">
              {['xs', 'sm', 'md', 'lg'].map((sh) => (
                <div key={sh} className={cn('aspect-square bg-[var(--bg-card)] rounded-lg flex flex-col items-center justify-center gap-1 p-4 shadow-' + sh, 'border border-[var(--border-subtle)] transition-colors')}>
                  <span className="text-[12px] font-semibold text-[var(--text-main)] uppercase transition-colors">{sh}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* 04 BUTTONS */}
      <section id="buttons" className="sg-section mb-20 pb-20 border-b border-[var(--border-subtle)]">
        <SectionHeader num="04 — Buttons" title="Buttons & CTAs" desc="Two grammars: pills for high-priority actions, rectangles for site navigation." />
        
        <Label>Variants</Label>
        <div className="flex flex-wrap items-center gap-3 mb-12">
          <Button variant="primary">Accept all</Button>
          <Button variant="secondary">Learn more</Button>
          <Button variant="accent">Get started →</Button>
          <Button variant="ghost">Cancel</Button>
          <Button variant="link">View details</Button>
        </div>

        <Label>Pill System (Theme Reactive)</Label>
        <div className="flex flex-wrap items-center gap-2 mb-12">
          <Pill variant="black">Black/White</Pill>
          <Pill variant="default">Neutral</Pill>
          <Pill variant="primary" dotColor="var(--accent-primary)">Primary</Pill>
          <Pill variant="secondary" dotColor="var(--accent-secondary)">Secondary</Pill>
          <Pill variant="tertiary" dotColor="var(--accent-tertiary)">Tertiary</Pill>
        </div>

        <Label>Status Badges</Label>
        <div className="flex flex-wrap items-center gap-2">
          <span className="badge badge-new bg-[var(--text-main)] text-[var(--bg-page)] transition-colors">New</span>
          <span className="badge bg-[var(--accent-tertiary)] text-white">−20%</span>
          <span className="badge border border-[var(--accent-secondary-glass)] bg-[var(--accent-secondary-glass)] text-[var(--accent-secondary)]">Beta</span>
          <span className="badge bg-gradient-to-br from-[var(--accent-tertiary)] to-[#FF6B6B] text-white">Pro</span>
        </div>
      </section>

      {/* 05 COMPONENTS */}
      <section id="components" className="sg-section mb-20 pb-20 border-b border-[var(--border-subtle)]">
        <SectionHeader num="05 — Components" title="UI Blueprints" desc="A comprehensive library of components refactored for the Studio theme engine." />
        
        <Label>Cards & Surfaces</Label>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-12">
          <Card variant="glass">
            <CardHeader className="aspect-video bg-gray-100/50 dark:bg-white/5 flex items-center justify-center text-[11px] tracking-wider uppercase text-gray-400 border-b border-[var(--border-subtle)] transition-colors duration-300">16:9 Media</CardHeader>
            <CardBody>
              <Label className="mb-1.5">Interactive Card</Label>
              <h3 className="font-display text-[18px] font-bold leading-tight mb-2 text-[var(--text-main)] transition-colors">50M+ Users Reached</h3>
              <p className="text-[13px] text-gray-500 dark:text-gray-400 transition-colors">Full-scale digital transformation for enterprise.</p>
            </CardBody>
            <CardFooter>
              <Pill variant="primary">Live</Pill>
              <Button variant="ghost" size="sm">View →</Button>
            </CardFooter>
          </Card>
          <Card variant="dark">
            <CardHeader className="aspect-video bg-black/40 flex items-center justify-center text-[11px] tracking-wider uppercase text-gray-500 border-b border-gray-800">Forced Dark</CardHeader>
            <CardBody>
              <Label className="mb-1.5">Fixed Context</Label>
              <h3 className="font-display text-[18px] font-bold text-white mb-2">Brand Agency</h3>
              <p className="text-[13px] text-gray-400">Complete brand systems for emerging organizations.</p>
            </CardBody>
            <CardFooter className="border-gray-800">
              <Pill variant="default" className="bg-white/10 text-gray-400 border-none">Strategy</Pill>
              <Button variant="ghost" size="sm" className="bg-white/10 text-gray-300 border-none">Explore</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardBody className="p-8">
              <div className="w-10 h-10 rounded-md bg-[var(--accent-tertiary-glass)] flex items-center justify-center mb-5 transition-colors"><Zap className="w-5 h-5 text-[var(--accent-tertiary)]" /></div>
              <h3 className="font-display text-[18px] font-bold text-[var(--text-main)] mb-2 transition-colors">Performance Score</h3>
              <p className="text-[13px] text-gray-500 dark:text-gray-400 transition-colors">Core Web Vitals optimized. Lighthouse 98+. Built for speed.</p>
            </CardBody>
          </Card>
        </div>

        <Label>Form Selections & Inputs</Label>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-10 mb-12">
          <div className="space-y-5">
            <div className="grid grid-cols-2 gap-4">
              <Input label="First Name" placeholder="Cody" />
              <Input label="Last Name" placeholder="Reich" />
            </div>
            <Input label="Email Address" placeholder="hello@monicore.com" icon={<Mail />} hint="We'll never share your email." />
            <Textarea label="Project Scope" rows={3} placeholder="Tell us about your needs..." />
            <Input label="Validation Example" value="invalid@" error hint="Please enter a valid email address." />
          </div>
          <div className="p-8 bg-[var(--bg-surface)] dark:bg-white/5 border border-[var(--border-subtle)] rounded-lg flex flex-col justify-between transition-colors">
            <div className="space-y-5">
               <Label>Checkboxes</Label>
               <Checkbox label="Performance Analytics" checked />
               <Checkbox label="Cloud Infrastructure" checked />
               <Checkbox label="SEO Marketing" />
            </div>
            <div className="h-px bg-[var(--border-subtle)] my-4 transition-colors" />
            <div className="space-y-5">
               <Label>Radios & Toggles</Label>
               <div className="flex gap-8">
                 <Radio label="Monthly" selected />
                 <Radio label="Annual" />
               </div>
               <div className="flex items-center justify-between">
                 <Toggle label="Email Alerts" on />
                 <Toggle label="Safe Mode" />
               </div>
            </div>
          </div>
        </div>

        <Label>Progress & Data Objects</Label>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-10 mb-12">
          <div className="space-y-8">
            <Progress label="Overall Progress" value={87} />
            <Progress label="Database Migration" value={64} colorClass="bg-[var(--accent-secondary)]" />
            <Progress label="Asset Optimization" value={32} colorClass="bg-[var(--accent-tertiary)]" />
            
            <div className="table-wrap transition-colors">
              <table className="sg-table">
                <thead>
                  <tr><th>Client</th><th>Status</th><th>Growth</th></tr>
                </thead>
                <tbody className="transition-colors">
                  <tr>
                    <td><div className="flex items-center gap-3"><Avatar initials="AR" size="sm" className="bg-[var(--accent-secondary-glass)] text-[var(--accent-secondary)]" /><span>Atlantic</span></div></td>
                    <td><Pill variant="primary" className="scale-90 origin-left">Live</Pill></td>
                    <td className="text-green-600 font-bold">+12%</td>
                  </tr>
                  <tr>
                    <td><div className="flex items-center gap-3"><Avatar initials="CC" size="sm" className="bg-[var(--accent-tertiary-glass)] text-[var(--accent-tertiary)]" /><span>Cherry</span></div></td>
                    <td><Pill variant="secondary" className="scale-90 origin-left">Active</Pill></td>
                    <td className="text-green-600 font-bold">+8%</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div className="flex flex-col justify-center items-center bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-lg p-10 transition-colors">
             <Avatar initials="CR" size="lg" className="mb-4 bg-[var(--accent-primary)] text-[var(--accent-primary-contrast)] border-none" />
             <span className="text-[16px] font-bold text-[var(--text-main)] transition-colors">Cody Reich</span>
             <span className="text-[12px] text-gray-500 mb-8 transition-colors">Design Director</span>
             <AvatarGroup>
                <Avatar initials="MV" className="bg-[var(--accent-secondary-glass)] text-[var(--accent-secondary)]" />
                <Avatar initials="AK" className="bg-[var(--accent-tertiary-glass)] text-[var(--accent-tertiary)]" />
                <Avatar initials="JS" className="bg-gray-200 text-gray-600" />
                <Avatar initials="+12" size="sm" className="bg-[var(--text-main)] text-[var(--bg-page)] border-none" />
             </AvatarGroup>
             <div className="mt-8 flex gap-4">
                <div className="text-center"><div className="text-[18px] font-bold text-[var(--text-main)]">142</div><div className="text-[10px] uppercase text-gray-400">Projects</div></div>
                <div className="w-px bg-[var(--border-subtle)]" />
                <div className="text-center"><div className="text-[18px] font-bold text-[var(--text-main)]">98</div><div className="text-[10px] uppercase text-gray-400">Score</div></div>
             </div>
          </div>
        </div>

        <Label>Alert Messaging</Label>
        <div className="max-w-[680px] mb-12">
          <Alert variant="info" title="System Maintenance">Scheduled downtime for server upgrades this Saturday at 2 AM UTC.</Alert>
          <Alert variant="success" title="Access Granted">Your API keys have been verified and access is now active.</Alert>
          <Alert variant="warning" title="Incomplete Profile">Please upload a valid profile photo to complete onboarding.</Alert>
          <Alert variant="danger" title="Security Breach">Unauthorized login attempt detected from a new location.</Alert>
        </div>

        <Label>Stat Matrix</Label>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-12">
          {[
            { label: 'Reach', value: '50M+', delta: '↑ 12%', trend: 'up', icon: <Globe /> },
            { label: 'Uptime', value: '99.9%', delta: 'Stable', trend: 'up', icon: <Activity /> },
            { label: 'Clusters', value: '14', delta: '↓ 2pts', trend: 'down', icon: <Layers /> },
            { label: 'Security', value: 'Level 4', delta: 'Active', trend: 'up', icon: <Shield /> },
          ].map((stat) => (
            <div key={stat.label} className="p-6 bg-[var(--bg-card)] border border-[var(--border-subtle)] rounded-lg transition-all hover:border-[var(--accent-primary)] group">
              <div className="w-8 h-8 rounded-md bg-[var(--bg-surface)] dark:bg-white/5 flex items-center justify-center text-[var(--accent-secondary)] mb-4 group-hover:scale-110 transition-transform">
                {stat.icon && React.cloneElement(stat.icon as any, { size: 16 })}
              </div>
              <div className="text-[28px] font-display font-bold text-[var(--text-main)] leading-none mb-1 transition-colors">{stat.value}</div>
              <div className="text-[12px] text-gray-500 mb-2 transition-colors">{stat.label}</div>
              <div className={cn("text-[10px] font-bold uppercase tracking-wider transition-colors", stat.trend === 'up' ? "text-green-600" : "text-red-600")}>{stat.delta}</div>
            </div>
          ))}
        </div>
      </section>

      {/* 06 LAYOUT */}
      <section id="layout" className="sg-section mb-20 pb-20 border-b border-[var(--border-subtle)]">
        <SectionHeader num="06 — Layout" title="Layout Patterns" desc="Standardized navigation structures and hero treatments." />
        
        <Label>Interface Stack</Label>
        <div className="border border-[var(--border-subtle)] rounded-lg overflow-hidden mb-12 bg-[var(--bg-card)] transition-colors">
          <div className="h-14 px-6 flex items-center justify-between border-b border-[var(--border-subtle)] transition-colors">
            <div className="font-display font-bold text-[16px] text-[var(--text-main)] transition-colors">{identity.brandName}</div>
            <div className="hidden md:flex gap-6">
              {['Services', 'Work', 'Vision', 'News'].map(l => (
                <a key={l} href="#" className="text-[13px] font-medium text-gray-500 hover:text-[var(--text-main)] transition-colors">{l}</a>
              ))}
            </div>
            <Button variant="accent" size="sm">Get Access</Button>
          </div>
          <div className="h-11 bg-[var(--bg-surface)] dark:bg-white/5 px-6 flex items-center gap-1 transition-colors">
            {['Dashboard', 'Team', 'Projects', 'Assets'].map((l, i) => (
              <a key={l} href="#" className={cn('text-[12px] font-medium px-3 py-1.5 rounded-md transition-all', i === 0 ? 'bg-[var(--bg-card)] text-[var(--text-main)] shadow-sm' : 'text-gray-500 hover:text-[var(--text-main)]')}>{l}</a>
            ))}
          </div>
        </div>

        <Label>Edge-to-Edge Logic</Label>
        <div className="grid grid-cols-1 md:grid-cols-2 border border-[var(--border-subtle)] rounded-lg overflow-hidden transition-colors">
          <div className="p-12 aspect-square flex flex-col justify-between bg-[var(--fixed-black)] text-white">
             <div>
               <p className="text-[11px] uppercase tracking-widest opacity-50 mb-3">Enterprise · Studio</p>
               <h3 className="font-display text-[32px] font-bold leading-tight">Professional<br />Handoff Tools</h3>
             </div>
             <Button variant="accent" size="sm" className="w-fit">View Spec</Button>
          </div>
          <div className="p-12 aspect-square flex flex-col justify-between bg-[var(--accent-primary)] text-[var(--accent-primary-contrast)]">
             <div>
               <p className="text-[11px] uppercase tracking-widest opacity-50 mb-3">Custom · Palette</p>
               <h3 className="font-display text-[32px] font-bold leading-tight">Adaptive Brand<br />Consistency</h3>
             </div>
             <Button variant="ghost" size="sm" className="w-fit bg-white/10 text-inherit border-white/20">Learn More</Button>
          </div>
        </div>
      </section>

      {/* 07 MOTION */}
      <section id="motion" className="sg-section mb-20 pb-20 border-b border-[var(--border-subtle)]">
        <SectionHeader num="07 — Motion" title="Animation Language" desc="Motion reinforces meaning. Entrances are gentle, exits are swift, hover states are immediate." />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[
            { name: 'Fade Up', spec: 'opacity: 0→1 + translateY(8px→0) · 400ms', use: 'Page sections, scroll reveal', anim: { initial: { opacity: 0, y: 8 }, whileHover: { opacity: 1, y: 0 } } },
            { name: 'Scale In', spec: 'scale(0.85→1) + opacity · 300ms', use: 'Modals, dropdowns, tooltips', anim: { initial: { opacity: 0, scale: 0.85 }, whileHover: { opacity: 1, scale: 1 } } },
            { name: 'Slide Right', spec: 'translateX(-8px→0) + opacity · 250ms', use: 'List items, navigation drawers', anim: { initial: { opacity: 0, x: -8 }, whileHover: { opacity: 1, x: 0 } } },
            { name: 'Bounce In', spec: 'scale(0.9→1.05→1) · 500ms spring', use: 'Success badges, primary interactions', anim: { initial: { scale: 0.9 }, whileHover: { scale: [0.9, 1.05, 1] } } },
          ].map((m) => (
            <motion.div key={m.name} initial="initial" whileHover="whileHover" className="flex items-center gap-5 p-6 border border-[var(--border-subtle)] bg-[var(--bg-card)] rounded-lg transition-all hover:border-[var(--accent-primary)] group cursor-default">
              <div className="w-14 h-14 bg-[var(--bg-surface)] dark:bg-white/5 rounded-md flex items-center justify-center overflow-hidden transition-colors">
                <motion.div variants={m.anim} className="w-6 h-6 bg-[var(--accent-primary)] rounded-sm" />
              </div>
              <div className="flex-1">
                <div className="text-[14px] font-bold text-[var(--text-main)] transition-colors">{m.name}</div>
                <div className="font-mono text-[11px] text-gray-400">{m.spec}</div>
                <div className="text-[12px] text-gray-500 mt-1 transition-colors">{m.use}</div>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* 08 TOKENS */}
      <section id="tokens">
        <SectionHeader num="08 — Tokens" title="Monicore Studio Spec" desc="The technical single source of truth. All decisions are expressed as CSS properties." />
        <div className="bg-gray-900 dark:bg-black text-[#E4E4E4] rounded-md p-8 font-mono text-[13px] leading-[1.7] overflow-x-auto mb-10 border border-[var(--border-subtle)] transition-colors">
          <p className="text-[#6B6B6B]">/* ─── Monicore Technical Blueprint ─── */</p>
          <p className="text-[#79C0FF]">@theme <span className="text-white">{"{"}</span></p>
          <div className="pl-4">
            <p><span className="text-[#79C0FF]">--bg-page</span>: <span className="text-[#A8C9A0]">{theme === 'light' ? '#FAFAFA' : '#0A0A0A'}</span>;</p>
            <p><span className="text-[#79C0FF]">--text-main</span>: <span className="text-[#A8C9A0]">{theme === 'light' ? '#0A0A0A' : '#FAFAFA'}</span>;</p>
            <p><span className="text-[#79C0FF]">--accent-primary</span>: <span className="text-[#A8C9A0]">{colors.primary}</span>;</p>
            <p><span className="text-[#79C0FF]">--font-display</span>: <span className="text-[#A8C9A0]">{fonts.display}</span>;</p>
            <p><span className="text-[#79C0FF]">--radius-lg</span>: <span className="text-[#F0A070]">{radii.lg}px</span>;</p>
          </div>
          <p className="text-white">{"}"}</p>
        </div>
        <Label>Production Exports</Label>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {['CSS', 'MD'].map(type => (
            <button key={type} onClick={() => handleExport(type)} className="p-4 border border-[var(--border-subtle)] rounded-md flex items-center gap-3 hover:border-[var(--accent-primary)] transition-all text-left bg-[var(--bg-card)]">
              <div className="w-9 h-9 rounded-md flex items-center justify-center text-[11px] font-bold bg-[var(--text-main)] text-[var(--bg-page)] transition-colors duration-300">{type}</div>
              <div className="flex-1 text-[13px] font-semibold text-[var(--text-main)] transition-colors">{type} Specification</div>
              <Download className="w-3.5 h-3.5 text-gray-300" />
            </button>
          ))}
        </div>
      </section>
    </div>
  );
}
